org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
minecraft_version_range=[26.1,26.3)
forge_version=65.0.1

mod_version=0.1.0
mod_group_id=net.palasitemclear
mod_id=palasitemclear
mod_name=Pala's Item Clear
mod_license=MIT
