org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.10
minecraft_version_range=[1.21.5,1.21.11)
fabric_minecraft_version_range=>=1.21.5- <1.21.11-
loader_version=0.19.3
loom_version=1.11.456
filter_tier=components-2
java_release=21

mod_version=0.1.0
maven_group=net.palasitemclear
fabric_api_version=0.138.4+1.21.10
yarn_mappings=1.21.10+build.3