org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.5)
loader_version=0.16.9
loom_version=1.10.455
filter_tier=components
java_release=21

mod_version=0.1.0
maven_group=net.palasitemclear
fabric_api_version=0.102.0+1.21.1
yarn_mappings=1.21.1+build.3